# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install sqlite3
      run: sudo apt-get install libsqlite3-dev
      
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.2.0
      with:
        # Private SSH key to register in the SSH agent
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
    - run: echo "::set-output name=RUBY_VERSION::$(cat .ruby-version)"
      id: rbenv
      
    - name: Set up Ruby
      #uses: actions/setup-ruby@v1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ steps.rbenv.outputs.RUBY_VERSION }}"
      
    - name: Restore Bundler cache
      id: cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundle-
      
    - name: Install bundler
      run: gem install bundler --no-document
      
    - name: Install bundles
      run: bundle install --deployment --jobs=4 --without=production
      
    - name: Capistrano deploy
      run: bundle exec cap staging deploy

